Update tsx
Try to fix build error:

Error: tsx must be loaded with --import instead of --loader
The --loader flag was deprecated in Node v20.6.0

https://github.com/privatenumber/tsx/issues/421